#
# (C) Copyright 2000, 2001, 2002
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += ../common/eeprom.o
obj-y += igep00x0.o
obj-$(CONFIG_LED_STATUS) += ../common/led.o
