#
# Makefile
#
# Copyright (C) 2016, ISEE 2007 SL - http://www.isee.biz/
#
# SPDX-License-Identifier:	GPL-2.0+
#

ifdef CONFIG_SPL_BUILD
obj-y	+= mux.o
endif

obj-y += ../common/eeprom.o

obj-y += board.o
obj-y += led.o
